---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: ksh module test 
    ksh_custom_module:
      name: phil
      condition: busy
    register: ksh_output

  - debug: 
      var: ksh_output
